version: '3.7'

services:
    logstash:
        container_name: sf_logstash
        build:
            context: docker/elk/logstash
        volumes:
            - ./srv/var/log:/var/log/other:cached
        depends_on:
            - elasticsearch
        restart: on-failure
        ports:
          - '5044:5044'

    kibana:
        container_name: sf_kibana
        build:
            context: docker/elk/kibana
        depends_on:
            - elasticsearch
            - logstash
        restart: on-failure
        ports:
            - '5601:5601'
