version: '3.7'

services:
    app:
        depends_on:
            - mysql

    mysql:
        container_name: sf_mysql
        image: mysql:latest
        command:
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
            - '--default-authentication-plugin=mysql_native_password'
            - '--lower_case_table_names=0'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password
        volumes:
            - ../var/data/mysql:/var/lib/mysql:rw
            - ./db:/docker-entrypoint-initdb.d
        ports: ['3306:3306']
        restart: on-failure
