version: '3.7'

services:
    app:
        depends_on:
            - mysql

    mysql:
        container_name: ${APP_NAME}_mysql
        image: mysql:latest
        command:
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
            - '--default-authentication-plugin=mysql_native_password'
            - '--lower_case_table_names=0'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./.data/mysql:/var/lib/mysql:rw,delegated
            - ./docker/db:/docker-entrypoint-initdb.d
        ports: ['3306:3306']
        restart: on-failure
