version: '3.7'

services:
    app:
        environment:
            - APP_HTTP_CACHE=0
            - APP_TRUSTED_PROXIES=varnish
            - HTTPCACHE_PURGE_SERVER=http://varnish
            - HTTPCACHE_PURGE_TYPE=http

    varnish:
        build:
            context: docker/varnish
        ports:
            - '8081:80'
        environment:
            - VARNISH_MALLOC_SIZE=256m
        depends_on:
            - nginx
            - app
        #command: ['--acl-add', 'app']
        restart: on-failure
