version: '3.7'

services:
	app:
		depends_on:
			- mariadb

	mariadb:
		container_name: ${APP_NAME}_mariadb
		image: mariadb:latest
		environment:
			MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
			MYSQL_DATABASE: ${MYSQL_DATABASE}
			MYSQL_USER: ${MYSQL_USER}
			MYSQL_PASSWORD: ${MYSQL_PASSWORD}
		volumes:
			- ./.data/mariadb:/var/lib/mariadb:rw,delegated
			- ./docker/db:/docker-entrypoint-initdb.d
		ports: ['3306:3306']
		restart: on-failure
