version: '3.7'

services:
    app:
        depends_on:
            - mariadb

    mariadb:
        container_name: sf_mariadb
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            DATABASE_URL: mysql://db_user:db_password@sf_mysql:3306/db_name
        volumes:
            - ./srv/var/data/mariadb:/var/lib/mariadb:rw
            - ./docker/db:/docker-entrypoint-initdb.d
        ports: ['3306:3306']
        restart: on-failure
